apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
      - name: api-server
        image: riadflh/kubeproject-node-api:latest
        ports:
        - containerPort: 3000
        envFrom: 
          - configMapRef: 
              name: app-config
        env: 
          - name: REDIS_PASSWORD
            valueFrom: 
              secretKeyRef: 
                name: redis-password
                key: redis_password
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql_root_pass


       
--- 

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: node-app-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-server
  minReplicas: 1
  maxReplicas: 5 
  targetCPUUtilizationPercentage: 50  


---

apiVersion: v1
kind: Service
metadata:
  name: api-server
  labels:
    app: api-server
spec:
  type: LoadBalancer    
  ports:
    - port: 80            
      targetPort: 3000      
  selector:
    app: api-server           

