apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: "mysql"
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql_root_pass
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        - name: init-script-volume
          mountPath: /docker-entrypoint-initdb.d/init.sql
          subPath: init.sql
      volumes:
        - name: init-script-volume
          configMap:
            name: mysql-init-script
  volumeClaimTemplates:
  - metadata:
      name: mysql-storage
    spec:
      storageClassName: sc-local
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

