apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-server
  template:
    metadata:
      labels:
        app: worker-server
    spec:
      containers:
      - name: worker-server
        image: riadflh/kubeproject-node-worker:latest
        ports:
        - containerPort: 3000
        envFrom:
          - configMapRef:
              name: app-config
        env:
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-password
                key: redis_password
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql_root_pass




--- 

apiVersion: v1
kind: Service
metadata:
  name: worker-server
  labels:
    app: worker-server
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: worker-server

